export class stkPriceBoard {
    constructor() {
        this.itemName = null; // -- name of stock node
        // t15 = ''; //-- stock id
        // t17: number = 0; //-- dateNo
        this.t31 = 0; // -- MatchPrice
        this.t31_incr = 0.00; // -- Giá trị tăng giảm
        this.t31_incr_per = 0.00; // -- tỷ lệ tăng giảm
        this.t31_color = ''; // -- MatchPrice
        this.t32 = 0; // -- MatchQty
        // t33 = ''; //-- ActionTyle;//Loai khop A: Khop chinh; B Tam Khop
        // t52 = ''; //-- Time
        this.t55 = ''; // -- stock code
        // t106 = ''; //-- Issuer
        // t107 = ''; //-- SecurityDesc
        // t109: number = 0; //-- TotalListingQtty
        // t132: number = 0; //-- BestBidPrice
        // t133: number = 0; //-- BestOfferPrice
        // t134: number = 0; //-- TotalBidQtty
        // t135: number = 0; //-- TotalOfferQtty
        // t136: number = 0; //--
        this.t137 = 0; // -- OpenPrice Giá mở cửa
        this.t137_color = ''; // -- OpenPrice
        // t138: number = 0; //-- PriorOpenPrice
        this.t139 = 0; // -- ClosePrice
        this.t139_color = ''; // -- ClosePrice
        // t140: number = 0; //-- PriorClosePrice
        // t167 = ''; //-- SecurityType
        // t223 = ''; //-- CouponRate
        // t225 = ''; //-- IssueDate
        // t230: number = 0; //-- AdjustQtty
        // t232 = ''; //-- ReferenceStatus
        // t233: number = 0; //-- AdjustRate
        // t244: number = 0; //-- DividentRate
        // t255: number = 0; //-- CurrentPrice
        this.t260 = 0; // -- BasicPrice
        this.t266 = 0; // -- HighestPrice Giá cao nhất
        this.t266_color = ''; // -- HighestPrice
        // t277: number = 0; //-- PriorPrice
        // t310: number = 0; //-- MatchValue
        // t320: number = 0; //-- OfferCount
        // t321: number = 0; //-- BidCount
        // t326 = ''; //-- SecurityTradingStatus
        // t327 = ''; //-- ListingStatus
        this.t332 = 0; // -- CeilingPrice
        this.t333 = 0; // -- FloorPrice
        // t334: number = 0; //-- Parvalue
        // t336 = ''; //-- TradingSessionID
        // t340 = ''; //-- TradSesStatus
        this.t387 = 0; // -- TotalVolumeTraded
        // t388: number = 0; //-- Tradingdate
        // t391: number = 0; //-- NMTotalTradedQtty
        // t392: number = 0; //-- NMTotalTradedValue
        // t393: number = 0; //-- PTMatchQtty
        // t394: number = 0; //-- PTTotalTradedQtty
        // t395: number = 0; //-- TotalBuyTradingQtty
        // t396: number = 0; //-- TotalSellTradingQtty
        this.t397 = 0; // -- BuyForeignQtty
        this.t398 = 0; // -- SellForeignQtty
        // t399 = ''; //-- time
        // t400: number = 0; //-- TradingUnit
        // t425 = ''; //-- BoardCode
        // t541 = ''; //-- MaturityDate
        this.t631 = 0; // -- MidPx Giá trung bình
        this.t631_color = ''; // -- MidPx
        // t1321: number = 0; //-- BestBidQtty
        // t1331: number = 0; //-- BestOfferQtty
        // t1341: number = 0; //-- TotalBidQttyOD
        // t1351: number = 0; //-- TotalOfferQttyOD
        // t2551: number = 0; //-- CurrentQtty
        this.t2661 = 0; // -- LowestPrice Giá thấp nhất
        this.t2661_color = ''; // -- LowestPrice
        this.t3301 = 0; // -- RemainForeignQtty
        this.t3871 = 0; // -- TotalValueTraded
        // t3931: number = 0; //-- PTMatchPrice
        // t3941: number = 0; //-- PTTotalTradedValue
        // t3951: number = 0; //-- BuyCount
        // t3952: number = 0; //-- TotalBuyTradingValue
        // t3961: number = 0; //-- SellCount
        // t3962: number = 0; //-- TotalSellTradingValue
        this.t3971 = 0; // -- BuyForeignValue
        this.t3981 = 0; // -- SellForeignValue
        this.seq = 0; // -- seq
        this.U6 = ''; // -- U6
        this.U7 = ''; // -- U7
        this.U8 = ''; // -- U8
        this.U9 = ''; // -- U9
        this.U10 = ''; // -- San giao dich
        this.t555 = 0; // -- Top price
        this.t556_1 = 0; // -- NumTopPrice
        this.t132_1 = 0; // -- BestBidPrice Giá dư mua 1
        this.t132_1_color = ''; // -- BestBidPrice
        this.t1321_1 = 0; // -- BestBidQtty
        this.t133_1 = 0; // -- BestOfferPrice Giá dư bán 1
        this.t133_1_color = ''; // -- BestOfferPrice
        this.t1331_1 = 0; // -- BestOfferQtty
        this.t556_2 = 0; // -- NumTopPrice
        this.t132_2 = 0; // -- BestBidPrice Dư mua giá 2
        this.t132_2_color = ''; // -- BestBidPrice
        this.t1321_2 = 0; // -- BestBidQtty
        this.t133_2 = 0; // -- BestOfferPrice Giá dư bán 2
        this.t133_2_color = ''; // -- BestOfferPrice
        this.t1331_2 = 0; // -- BestOfferQtty
        this.t556_3 = 0; // -- NumTopPrice
        this.t132_3 = 0; // -- BestBidPrice Dư mua giá 3
        this.t132_3_color = ''; // -- Cột màu tương ứng
        this.t1321_3 = 0; // -- BestBidQtty
        this.t133_3 = 0; // -- BestOfferPrice Giá dư bán 3
        this.t133_3_color = ''; // -- BestOfferPrice
        this.t1331_3 = 0; // -- BestOfferQtty
        this.t556_4 = 0; // -- NumTopPrice
        this.t132_4 = 0; // -- BestBidPrice
        this.t1321_4 = 0; // -- BestBidQtty
        this.t133_4 = 0; // -- BestOfferPrice
        this.t1331_4 = 0; // -- BestOfferQtty
        this.U17 = 0; // -- BestOfferQtty
        this.U18 = 0; // -- BestOfferQtty
        this.U24 = null; // CK cơ sở (cho Chứng quyền)
        this.U22 = 0; // Giá thực hiện (cho Chứng quyền)
        this.U23 = null; // Tỷ lệ chuyển đổi (cho Chứng quyền)
        this.t109 = 0; //  Khối lượng niêm yết (cho Chứng quyền)
        this.U20 = null; // Ngày Đáo hạn
        this.U21 = null; // Ngày GD gần nhất
        this.U19 = null; // Loại chứng quyền
        this.U29 = 0; // Giá trần dự kiến
        this.U30 = 0; // Giá sàn dự kiến
        this.U31 = 0; //Giá tham chiếu dự kiến
    }
}
