
export default {
    GET_SERVER_TIME: 'GET_SERVER_TIME',
    GET_RIGHTS_INFO: 'GET_RIGHTS_INFO',
    RIGHTSCR_001: 'RIGHTSCR_001',
    RIGHTSCR_002: 'RIGHTSCR_002',
    SUBSCRIBE_INDEX: 'SUBSCRIBE-INDEX',
    GETSTOCK_01: 'GETSTOCK-01',
    UNSUBSCRIBE_INDEX: 'UNSUBSCRIBE-INDEX',
    ADD_STK2FVL: 'ADD_STK2FVL',
    REMOVE_STKFVL: 'REMOVE_STKFVL',
    RECOMMSTK_001: 'RECOMMSTK_001',
    SUBSCRIBE_INDEX_SCROLL: 'SUBSCRIBE-INDEX-SCROLL',
    SUBSCRIBE_INDEX_REAL_TIME: 'SUBSCRIBE_INDEX_REAL_TIME',
    SUBSCRIBE_FVL_ONE: 'SUBSCRIBE_FVL_ONE',
    UNSUBSCRIBE_FVL: 'UNSUBSCRIBE_FVL',
    UNSUBSCRIBE: 'UNSUBSCRIBE',
    getStk_list: 'GET_STKLIST',


    reqTimeout: 25000, // 25 seconds




  };
  